#!/bin/bash
rm /dev/snake0
rm /dev/snake1
rm /dev/snake2
rm /dev/snake3
rmmod snake

make
insmod ./snake.o maxGames=10
mknod /dev/snake0 c 254 0
mknod /dev/snake1 c 254 1
mknod /dev/snake2 c 254 2
mknod /dev/snake3 c 254 3

gcc -Wall HW4-Test.c -o test_snake
./test_snake